### ISSUE TITLE
docker-compose up --build doesn't work

### ISSUE THREAD

**Issue by tadeuqc** [aayani/pet-store#7] opened 2019-11-27 00:09 UTC
basically all the container are throwing the same error:  

> Error: Cannot find module '/usr/src/app/dist/server.js'

**Comment by aayani** [comment] 2019-11-27 07:43
The project currently doesn't have a script for building node projects. Have you tried building them individually first?
```
cd owners
yarn
yarn build
```
```
cd owners
yarn
yarn build
```

**Comment by aayani** [comment] 2020-06-07 12:49
The issue is fixed and resolved with Docker multi-stage build

**Closed by aayani** 2020-06-07 12:49 UTC
